# Default settings for servicex. This will point you to a developer end-point, that
# you've setup on your own machine (usually using k8's port-forward command):

api_endpoints:
  - endpoint: http://localhost:5000
    name: default
    type: xaod
    # token: xxx

# This is the path of the cache. The "/tmp" will be translated, platform appropriate, and
# the env variable USER will be replaced.
cache_path: /tmp/servicex_${USER}

# This is a dummy value, here only to make sure that unit testing
# works properly before package release.
testing_value: 10

# If we can't figure out what backend the user is going to use, we
# return this sort of file. Parquet for the uproot backend, and root for the
# xaod backend.
default_return_data: parquet

# Defaults for the various types of servicex backends that we might deal with.
# Easy enough to add a new one here...
backend_types:
  - type: xaod
    return_data: root
  - type: uproot
    return_data: parquet
  - type: cms_run1_aod
    return_data: root
